# The Joiner component joins the streams `tenants` and `power_readings`
apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  streams:
    - tenants
    - power_readings
  window: 14s
  select:
    data: |
      {
        "customer_id": tenants.customer_id,
        "tenant_id": tenants.tenant_id,
        "tenant_usage": power_readings.tenant_usage
      }
    where: |
      tenants.tenant_id = power_readings.tenant_id
        && power_readings.current_usage >= 0.85

  servicePort: 8080
  target: billable-proc/billables