# The Joiner component joins the streams `tenants` and `power_readings`
apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: join-tenants-poweruse
  namespace: default
spec:
  servicePort: 8080
  window: 20s
  stream:
    from:
      - tenants
      - poweruse
    to:
      - component: billable-proc/billables
    select: |
      {
        "customer_id": tenants.customer_id,
        "tenant_id": tenants.tenant_id,
        "tenant_kwh_usage": poweruse.kwh_use
      }
    where: |
      tenants.tenant_id == poweruse.tenant_id
        && poweruse.power_use >= 1.0