# The Joiner component joins the streams `tenants` and `power_readings`
apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: join-tenants-poweruse
  namespace: default
spec:
  streams:
    - tenants
    - poweruse
  window: 20s
  select:
    data: |
      {
        "customer_id": tenants.customer_id,
        "tenant_id": tenants.tenant_id,
        "tenant_kwh_usage": poweruse.kwh_use
      }
    where: |
      tenants.tenant_id == poweruse.tenant_id
        && poweruse.power_use >= 1.0

  servicePort: 8080
  target: billable-proc/billables