apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: tenants
  namespace: default
spec:
  clusterStream: redis-stream
  topic: tenants
  route: /tenants
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: poweruse
  namespace: default
spec:
  clusterStream: rabbit-stream
  topic: poweruse
  route: /poweruse
