apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  servicePort: 8080
  window: 14s
  stream:
    from:
      - hello
      - goodbye
    to:
      - component: message-proc/messages
    select: |
      {"hello": hello, "goodbye":goodbye}
    where: |
      int(hello['id']) == 5 && goodbye.id == 5.0
