apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  streams:
  - hello-stream
  - goodbye-stream
  window: 14s
  expression: "hello.salutation == goodbye.salutation"
  servicePort: 8080
  target: message-proc/messages