apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  streams:
  - hello
  - goodbye
  window: 14s
  select:
    data: "string(hello.message.id) + '~' + hello.message.text"
    where: "int(hello.message['id']) > 5 && goodbye.message.id >= 5.0"
  servicePort: 8080
  target: message-proc/messages