apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: hello-stream
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "hello-stream"
  route: "/hello"
  recipients:
    - hello-goodbye-join
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: goodbye-stream
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "goodbye-stream"
  route: "/goodbye"
  recipients:
    - hello-goodbye-join