apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  streams:
  - hello-stream
  - goodbye-stream
  window: "100ms"
  expression: "hello.salutation == goodbye.salutation"
  servicePort: 8080
  container:
    name: hello-goodbye-join
    image: ghcr.io/vladimirvivien/streaming-runtime/components/joiner:latest
    imagePullPolicy: Always
  recipients:
    - messages