apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: hello
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "hello"
  route: "/hello"

---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: goodbye
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "goodbye"
  route: "/goodbye"
