apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.2.6-alpine
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syslog-gen
  name: syslog-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-gen
  template:
    metadata:
      annotations:
        dapr.io/app-id: syslog-gen
        dapr.io/enabled: "true"
      labels:
        app: syslog-gen
    spec:
      containers:
      - env:
        - name: MESSAGE_EXPR
          value: |
            [
              {"timestamp":"Jun 14 15:16:01", "process":"sshd(pam_unix)[19939]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4 "},
              {"timestamp":"Jun 14 15:16:02", "process":"sshd(pam_unix)[19937]", "message":"check pass; user unknown"},
              {"timestamp":"Jun 14 15:16:02", "process":"sshd(pam_unix)[19937]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4 "},
              {"timestamp":"Jun 15 02:04:59", "process":"sshd(pam_unix)[20882]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=220-135-151-1.hinet-ip.hinet.net  user=root"},
              {"timestamp":"Jun 15 02:04:59", "process":"sshd(pam_unix)[20884]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=220-135-151-1.hinet-ip.hinet.net  user=root"},
              {"timestamp":"Jun 15 02:04:59", "process":"sshd(pam_unix)[20883]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=220-135-151-1.hinet-ip.hinet.net  user=root"},
              {"timestamp":"Jun 15 02:04:59", "process":"sshd(pam_unix)[20885]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=220-135-151-1.hinet-ip.hinet.net  user=root"},
              {"timestamp":"Jun 15 04:06:18", "process":"su(pam_unix)[21416]", "message":"session opened for user cyrus by (uid=0)"},
              {"timestamp":"Jun 15 04:06:19", "process":"su(pam_unix)[21416]", "message":"session closed for user cyrus"},
              {"timestamp":"Jun 16 04:16:17", "process":"su(pam_unix)[25548]", "message":"session opened for user news by (uid=0)"},
              {"timestamp":"Jun 16 04:16:18", "process":"su(pam_unix)[25548]", "message":"session closed for user news"},
              {"timestamp":"Jun 17 04:03:33", "process":"su(pam_unix)[27953]", "message":"session opened for user cyrus by (uid=0)"},
              {"timestamp":"Jun 17 04:03:34", "process":"su(pam_unix)[27953]", "message":"session closed for user cyrus"},
              {"timestamp":"Jun 17 07:07:00", "process":"ftpd[29504]", "message":"connection from 24.54.76.216 (24-54-76-216.bflony.adelphia.net) "},
              {"timestamp":"Jun 17 07:07:00", "process":"ftpd[29508]", "message":"connection from 24.54.76.216 (24-54-76-216.bflony.adelphia.net)"},
              {"timestamp":"Jun 17 07:07:00", "process":"ftpd[29507]", "message":"connection from 24.54.76.216 (24-54-76-216.bflony.adelphia.net)"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14281]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14279]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14282]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14277]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14278]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 21 08:56:36", "process":"sshd(pam_unix)[14280]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=217.60.212.66  user=guest"},
              {"timestamp":"Jun 22 03:17:26", "process":"sshd(pam_unix)[16207]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=n219076184117.netvigator.com  user=root"},
              {"timestamp":"Jun 22 03:17:26", "process":"sshd(pam_unix)[16206]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=n219076184117.netvigator.com  user=root"},
              {"timestamp":"Jun 22 03:17:35", "process":"sshd(pam_unix)[16210]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=n219076184117.netvigator.com  user=root"},
              {"timestamp":"Jun 22 03:17:36", "process":"sshd(pam_unix)[16212]", "message":"authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=n219076184117.netvigator.com  user=root"}
            ]
        - name: CLUSTER_STREAM
          value: syslog-stream
        - name: STREAM_TOPIC
          value: syslog
        image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-gen:latest
        imagePullPolicy: Always
        name: syslog-gen
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Channel
metadata:
  name: syslog-channel
  namespace: default
spec:
  select:
    data: |
      {"ts": syslog.timestamp, "message":syslog.message}
    where: |
      syslog.process.startsWith("sshd")
        && syslog.message.startsWith("authentication failure")
        && syslog.message.contains("user=root")
  servicePort: 8080
  serviceRoute: syslog
  target:
    component: syslog-proc/syslog
---
apiVersion: streaming.vivien.io/v1alpha1
kind: ClusterStream
metadata:
  name: syslog-stream
  namespace: default
spec:
  properties:
    redisHost: redis:6379
    redisPassword: ""
  protocol: redis
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Processor
metadata:
  name: syslog-proc
  namespace: default
spec:
  container:
    image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-proc:latest
    imagePullPolicy: Always
    name: syslog-proc
  replicas: 1
  servicePort: 8080
  serviceRoute: syslog
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: greetings
  namespace: default
spec:
  clusterStream: syslog-stream
  recipients:
  - syslog-channel
  route: /syslog
  topic: syslog
