# permissions for end users to view clusterstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterstream-viewer-role
rules:
- apiGroups:
  - streaming.tanzu.vmware.com
  resources:
  - clusterstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming.tanzu.vmware.com
  resources:
  - clusterstreams/status
  verbs:
  - get
