# permissions for end users to edit clusterstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterstream-editor-role
rules:
- apiGroups:
  - streaming.tanzu.vmware.com
  resources:
  - clusterstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.tanzu.vmware.com
  resources:
  - clusterstreams/status
  verbs:
  - get
