# permissions for end users to view joiners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joiner-viewer-role
rules:
- apiGroups:
  - streaming.vivien.io
  resources:
  - joiners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming.vivien.io
  resources:
  - joiners/status
  verbs:
  - get
