# permissions for end users to edit kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkatopic-editor-role
rules:
- apiGroups:
  - streaming.vivien.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.vivien.io
  resources:
  - kafkatopics/status
  verbs:
  - get
