# permissions for end users to view processors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: processor-viewer-role
rules:
- apiGroups:
  - streaming.vivien.io
  resources:
  - processors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming.vivien.io
  resources:
  - processors/status
  verbs:
  - get
