apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.2.6-alpine
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message-gen
  name: message-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-gen
  template:
    metadata:
      annotations:
        dapr.io/app-id: message-gen
        dapr.io/enabled: "true"
      labels:
        app: message-gen
    spec:
      containers:
      - env:
        - name: MESSAGE_EXPR
          value: '{"id": id, "greeting":"hello", "location":"world", "timestamp":timestamp}'
        - name: CLUSTER_STREAM
          value: redis-stream
        - name: STREAM_TOPIC
          value: greetings
        image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-gen:latest
        imagePullPolicy: Always
        name: message-gen
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Channel
metadata:
  name: greetings-channel
  namespace: default
spec:
  servicePort: 8080
  stream:
    from:
    - greetings
    select: |
      {"newgreeting": greetings.greeting + " " + greetings.location + "!"}
    to:
    - stream: rabbit-stream/greetings-sink
    where: |
      int(greetings['id']) % 5 == 0
---
apiVersion: streaming.vivien.io/v1alpha1
kind: ClusterStream
metadata:
  name: rabbit-stream
  namespace: default
spec:
  properties:
    deliveryMode: "2"
    durable: "true"
    host: amqp://admin:@dm1n@rabbitmq.default.svc.cluster.local:5672
  protocol: rabbitmq
---
apiVersion: streaming.vivien.io/v1alpha1
kind: ClusterStream
metadata:
  name: redis-stream
  namespace: default
spec:
  properties:
    redisHost: redis:6379
    redisPassword: ""
  protocol: redis
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Processor
metadata:
  name: message-proc
  namespace: default
spec:
  container:
    image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-proc:latest
    imagePullPolicy: Always
    name: message-proc
  replicas: 1
  servicePort: 8080
  serviceRoute: greetings-sink
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: greetings
  namespace: default
spec:
  clusterStream: redis-stream
  recipients:
  - greetings-channel
  route: /greetings
  topic: greetings
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: greetings-sink
  namespace: default
spec:
  clusterStream: rabbit-stream
  recipients:
  - message-proc
  route: /greetings-sink
  topic: greetings-sink
