apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.2.6-alpine
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goodbye-message-gen
  name: goodbye-message-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodbye-message-gen
  template:
    metadata:
      annotations:
        dapr.io/app-id: goodbye-message-gen
        dapr.io/enabled: "true"
      labels:
        app: goodbye-message-gen
    spec:
      containers:
      - env:
        - name: MESSAGE_EXPR
          value: '{"id": id, "greeting":"hello World!!", "timestamp":timestamp, "side":"goodbye"}'
        - name: CLUSTER_STREAM
          value: redis-stream
        - name: STREAM_TOPIC
          value: goodbye
        image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-gen:latest
        imagePullPolicy: Always
        name: message-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-message-gen
  name: hello-message-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-message-gen
  template:
    metadata:
      annotations:
        dapr.io/app-id: hello-message-gen
        dapr.io/enabled: "true"
      labels:
        app: hello-message-gen
    spec:
      containers:
      - env:
        - name: MESSAGE_EXPR
          value: '{"id": id, "greeting":"hello World!!", "timestamp":timestamp, "side":"hello"}'
        - name: CLUSTER_STREAM
          value: redis-stream
        - name: STREAM_TOPIC
          value: hello
        image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-gen:latest
        imagePullPolicy: Always
        name: message-gen
---
apiVersion: streaming.vivien.io/v1alpha1
kind: ClusterStream
metadata:
  name: redis-stream
  namespace: default
spec:
  properties:
    redisHost: redis:6379
    redisPassword: ""
  protocol: redis
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Joiner
metadata:
  name: hello-goodbye-join
  namespace: default
spec:
  servicePort: 8080
  stream:
    from:
    - hello
    - goodbye
    select: |
      {"hello": hello, "goodbye":goodbye}
    to:
    - component: message-proc/messages
    where: |
      int(hello['id']) == 5 && goodbye.id == 5.0
  window: 14s
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Processor
metadata:
  name: message-proc
  namespace: default
spec:
  container:
    image: ghcr.io/vladimirvivien/streaming-runtime-examples/message-proc:latest
    imagePullPolicy: Always
    name: message-proc
  replicas: 1
  servicePort: 8080
  serviceRoute: messages
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: goodbye
  namespace: default
spec:
  clusterStream: redis-stream
  route: /goodbye
  topic: goodbye
---
apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: hello
  namespace: default
spec:
  clusterStream: redis-stream
  route: /hello
  topic: hello
