apiVersion: streaming.vivien.io/v1alpha1
kind: Channel
metadata:
  name: greetings-channel
  namespace: default
spec:
  servicePort: 8080
  serviceRoute: greetings
  select:
    data: '{"newgreeting": greetings.greeting + " " + greetings.location + "!"}'
    where: "int(greetings['id']) % 5 == 0"
  target: message-proc/greetings