apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: hello
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "messages"
  route: "/greetings"
  recipients:
    - message-chan