apiVersion: streaming.vivien.io/v1alpha1
kind: Stream
metadata:
  name: greetings
  namespace: default
spec:
  clusterStream: "redis-stream"
  topic: "greetings"
  route: "/greetings"
  recipients:
    - greetings-channel